[pytest]
markers =
	smoke: Build verification test

filterwarnings =
    ignore: WARNING the new order is not taken into account:UserWarning
    ignore::urllib3.exceptions.InsecureRequestWarning
    ignore::cryptography.utils.CryptographyDeprecationWarning
    ignore: Use ProtectionLevel enum instead:DeprecationWarning
    ignore: Use protection_level parameter instead:DeprecationWarning
    ignore: pkg_resources is deprecated as an API:DeprecationWarning

log_format=%(asctime)s %(levelname)s:%(name)s:%(message)s
log_date_format=%H:%M:%S %z
log_level=INFO
junit_logging=all
junit_family=xunit2
junit_log_passing_tests=0
asyncio_mode=auto
addopts = --last-failed-no-failures=none

#addopts = --pdbcls=IPython.terminal.debugger:Pdb
